### ISSUE TITLE
Buttons should have role=button so they behave like buttons

### ISSUE THREAD

**Issue by nickcolley** [openregister/openregister-java#311]
If you visit https://country.register.gov.uk/ using assistive tech like a screen reader the button will be read out as a link, and pressing space will not activate the button.

You'll need to add the attribute 'role=button' and the following JavaScript shim (which should be avaliable if you're using govuk_frontend_toolkit): 

https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/shim-links-with-button-role.js
https://github.com/alphagov/static/commit/3c9bc1bfa45537262c4c079f7d3219a32f96f121

**Comment by samcrang** [comment]
Thanks for the heads-up. Looks like it should be an easy thing to resolve—we've added this to our backlog but we'll keep this issue open until it's resolved.

Thanks 😄
