### ISSUE TITLE
Fail to use a different register with Docker

### ISSUE THREAD

**Issue by arnau** [openregister/openregister-java#384]
If I follow the steps in `RUNNING_LOCALLY.md` to use `school-type` instead of `country`, I get either a `Register undefined` or an exception `curl: (22) The requested URL returned error: 400 Bad Request` depending on the `ENVIRONMENT` value.

**Comment by michaelabenyohai** [comment]
This is because `school-type` no longer exists in alpha. Let me fix this.

**Comment by michaelabenyohai** [comment]
@arnau does this help?

https://github.com/openregister/openregister-java/pull/388

**Comment by arnau** [comment]
@michaelabenyohai it does, thanks!
